version: "3.9"

services:

  pleo-antaeus:
    build:
      dockerfile: ./app.Dockerfile
      context: .
    image: pleo-antaeus-app
    volumes:
      - pleo-antaeus-build-cache:/root/.gradle
    ports:
      - 7000:7000
    tty: true
    expose:
      - 7000
    stdin_open: true

  scheduler:
    build:
      dockerfile: ./scheduler.Dockerfile
      context: .
    image: pleo-antaeus-scheduler

 # quartz:
 #  image: cexbbartolome/quartz-http:latest

volumes:
  pleo-antaeus-build-cache: